//  implementation of interface auth version 2010-12-27 11:00
//  auto-generated by apimono

using IMVU.IDL;
using System;
using System.Collections.Generic;

public class auth {

    public Dictionary<string, object> signin(IContext ctx, idstring userid, password password)
    {
        Dictionary<string, object> _ = new Dictionary<string, object>();
        // your code goes here; add return values to '_'
        if (userid.str != "jwatte" || password.str != "123456")
        {
            throw new InvalidOperationException("Bad user name or password.");
        }
        UserSession sess = UserSession.Create(ctx, userid.str);
        _.Add("token", new idstring(sess.sid));
        return _;
    } // signin


    public Dictionary<string, object> signout(IContext ctx)
    {
        Dictionary<string, object> _ = new Dictionary<string, object>();
		if (ctx.Session != null)
		{
			ctx.Session.Invalidate(ctx);
		}
        // your code goes here; add return values to '_'
        return _;
    } // signout


    public Dictionary<string, object> verify(IContext ctx)
    {
        Dictionary<string, object> _ = new Dictionary<string, object>();
        _.Add("status", true);
        return _;
    } // verify

}; // class
